export const STAFF = {
    STORE_STUDENTS: "STORE_STUDENTS",
    TOGGLE_ROLL_MODE: "TOGGLE_ROLL_MODE",
    TOGGLE_BY_NAME: "TOGGLE_BY_NAME",
    TOGGLE_BY_ASCENDING: "TOGGLE_BY_ASCENDING",
    SEARCHED_BY_NAME: "SEARCHED_BY_NAME"
}