export const STAFF = {
    UPDATE_STUDENTS_WITH_UNMARK_TYPE: "UPDATE_STUDENTS_WITH_UNMARK_TYPE",
    TOGGLE_ROLL_MODE: "TOGGLE_ROLL_MODE",
    TOGGLE_BY_NAME: "TOGGLE_BY_NAME",
    TOGGLE_BY_ASCENDING: "TOGGLE_BY_ASCENDING",
    SEARCHED_BY_NAME: "SEARCHED_BY_NAME",
    UPDATE_STUDENT_WITH_NEW_ROLE: "UPDATE_STUDENT_WITH_NEW_ROLE",
    ADD_ROLL_STATE: "ADD_ROLL_STATE"
}